### ISSUE TITLE
Automatic compilation and deployment of docs

### ISSUE THREAD

**Issue by matthewmorek** [JasonEtco/flintcms-site#7]
Is there a chance you could add automatic deployment of docs to the site on push to `master`? Recent bits of info that were corrected and merged still do not appear on the live site.

**Comment by JasonEtco** [comment]
It'd require refactoring the way the site is built (I'd just opt for regular Jekyll + GitHub Pages vs. the existing Gulp setup), so yes I'm all for it I just need the time to do it. Will try to make it happen this weekend 👍

**Comment by JasonEtco** [comment]
Closed by #8
